/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_1024827_4[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale_1024827_4[3] = { 542.0117207516265, 318.4293225180887, 4755.723607328515 };
const float ei_classifier_anom_mean_1024827_4[3] = { 686.6048603537095, 416.7805980893236, 5358.833699595389 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_1024827_4[32] = {
	{ ( float[3] ) { 1.2442618608474731, 0.8338820934295654, 0.954359769821167 }, 0.3007225302434676 },
	{ ( float[3] ) { -0.01152988150715828, 0.19172823429107666, 0.9477117657661438 }, 9.313225746154785e-10 },
	{ ( float[3] ) { -0.9328435063362122, -0.8001537322998047, -1.0772340297698975 }, 0.13098305885952627 },
	{ ( float[3] ) { -1.0310122966766357, -0.9369845390319824, -1.088515281677246 }, 0.08381007902110574 },
	{ ( float[3] ) { 0.7061862945556641, 0.2676113545894623, 0.8830506801605225 }, 0.2364527029122601 },
	{ ( float[3] ) { -1.0107585191726685, -1.0344984531402588, -1.089619517326355 }, 0.06580544728947606 },
	{ ( float[3] ) { 0.9930880069732666, 1.1140849590301514, 0.990196943283081 }, 0.24514881449989312 },
	{ ( float[3] ) { 1.6487057209014893, 0.9985843896865845, 1.1508173942565918 }, 0.2641883947373177 },
	{ ( float[3] ) { 0.8647656440734863, 1.3515064716339111, 1.1227335929870605 }, 0.11896058909340146 },
	{ ( float[3] ) { 0.2840476632118225, 0.009210451506078243, 0.707000195980072 }, 0.25003527220836586 },
	{ ( float[3] ) { 0.5314116477966309, 1.0480458736419678, 0.9880427122116089 }, 0.19801807709811142 },
	{ ( float[3] ) { -0.9318371415138245, -0.42133864760398865, -1.0715909004211426 }, 0 },
	{ ( float[3] ) { 0.8492578268051147, 1.4883358478546143, 0.784564733505249 }, 0.2360342085306722 },
	{ ( float[3] ) { 0.873542070388794, 0.7173478007316589, 1.0684798955917358 }, 0.16416187732011014 },
	{ ( float[3] ) { -1.0995968580245972, -1.0704500675201416, -1.0944997072219849 }, 0.0737114956455539 },
	{ ( float[3] ) { 1.805145025253296, 2.0076587200164795, 0.7734256386756897 }, 0 },
	{ ( float[3] ) { 0.2638777494430542, 0.5009599328041077, 0.7438687086105347 }, 0.34244725447243435 },
	{ ( float[3] ) { 1.0829200744628906, 0.16448722779750824, 0.7981926202774048 }, 0.09345760462183413 },
	{ ( float[3] ) { 0.993525505065918, 0.42223894596099854, 0.747272789478302 }, 0.22115427115824512 },
	{ ( float[3] ) { 0.7963111996650696, 0.7974579930305481, 0.8206013441085815 }, 0.2581439851364451 },
	{ ( float[3] ) { 0.6343576312065125, 1.0452457666397095, 0.8032618761062622 }, 0.19323895527544038 },
	{ ( float[3] ) { 1.42466402053833, 2.5558555126190186, 0.6651564240455627 }, 0 },
	{ ( float[3] ) { 1.9127299785614014, 1.9270944595336914, 1.215919852256775 }, 0 },
	{ ( float[3] ) { 0.41515159606933594, 1.8112879991531372, 0.8786514401435852 }, 0 },
	{ ( float[3] ) { 2.072946786880493, 0.5040981769561768, 0.8539453744888306 }, 0 },
	{ ( float[3] ) { 1.2981951236724854, 3.02888560295105, 0.9876022338867188 }, 0 },
	{ ( float[3] ) { 0.004065502900630236, 0.3915327787399292, 0.5913559198379517 }, 0 },
	{ ( float[3] ) { 0.6243324279785156, -0.1728261560201645, 0.6407337188720703 }, 0 },
	{ ( float[3] ) { 1.1023515462875366, 2.154712438583374, 1.3950129747390747 }, 0 },
	{ ( float[3] ) { 1.2939339876174927, 0.05044811591506004, 1.0299485921859741 }, 0 },
	{ ( float[3] ) { 0.3835851550102234, 1.1863079071044922, 0.6185532212257385 }, 0 },
	{ ( float[3] ) { 2.342763900756836, 1.3894706964492798, 1.403185486793518 }, 0 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
